# Generated by Django 3.0.6 on 2020-05-27 20:33

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('altitude', models.FloatField(blank=True, max_length=100, null=True, verbose_name='Altitude')),
                ('latitude', models.FloatField(blank=True, max_length=100, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, max_length=100, null=True, verbose_name='Longitude')),
                ('coord_x', models.FloatField(blank=True, max_length=100, null=True, verbose_name='Coordenada X')),
                ('coord_y', models.FloatField(blank=True, max_length=100, null=True, verbose_name='Coordenada Y')),
                ('bacia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bacia')),
                ('distrito', models.CharField(blank=True, max_length=100, null=True, verbose_name='Distrito')),
                ('concelho', models.CharField(blank=True, max_length=100, null=True, verbose_name='Concelho')),
                ('freguesia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Freguesia')),
                ('responsavel_aut', models.CharField(blank=True, max_length=100, null=True, verbose_name='Entidade Responsável Automático')),
                ('responsavel_con', models.CharField(blank=True, max_length=100, null=True, verbose_name='Entidade Responsável Convencional')),
                ('estacao_aut', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Estação Automática')),
                ('estacao_con', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Estação Convencional')),
                ('entrada_con', models.DateTimeField(blank=True, null=True, verbose_name='Entrada Funcionamento Convencional')),
                ('encerra_con', models.DateTimeField(blank=True, null=True, verbose_name='Encerramento Convencional')),
                ('entrada_aut', models.DateTimeField(blank=True, null=True, verbose_name='Entrada Funcionamento Automática')),
                ('encerra_aut', models.DateTimeField(blank=True, null=True, verbose_name='Encerramento Automática')),
                ('telemetria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telemetria')),
                ('estado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('est_id', models.BigIntegerField(default=0, verbose_name='Estação ID')),
                ('geom', djgeojson.fields.PointField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_id', models.BigIntegerField(default=0, verbose_name='Parametro ID')),
                ('designacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Designacao')),
            ],
        ),
    ]
