# Generated by Django 3.0.6 on 2020-08-07 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_parametro_freq'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedParametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Estacao')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedEstacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Estacao')),
            ],
        ),
    ]
