# Generated by Django 3.0.6 on 2020-08-07 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_selectedestacao_selectedparametro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedparametro',
            name='estacao',
        ),
        migrations.AddField(
            model_name='selectedparametro',
            name='parametro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Parametro'),
        ),
        migrations.AlterField(
            model_name='selectedestacao',
            name='estacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Estacao'),
        ),
    ]
