# Generated by Django 3.0.6 on 2020-08-15 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_precipitacaodiaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstacaoParamUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('un', models.CharField(blank=True, max_length=10, null=True)),
                ('estacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Estacao')),
                ('parametro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Parametro')),
            ],
        ),
        migrations.RemoveField(
            model_name='selectedparametro',
            name='parametro',
        ),
        migrations.DeleteModel(
            name='SelectedEstacao',
        ),
        migrations.DeleteModel(
            name='SelectedParametro',
        ),
    ]
