# Generated by Django 3.0.6 on 2020-08-24 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200815_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='HidroExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rio')),
                ('area_drenada', models.FloatField(blank=True, max_length=100, null=True, verbose_name='Área Drenada')),
                ('cota_escala', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cota Zero Escala')),
                ('estacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Estacao')),
            ],
        ),
    ]
