# Generated by Django 3.0.6 on 2020-08-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_hidroextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hidroextra',
            name='cota_escala',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cota Zero Escala'),
        ),
        migrations.AlterField(
            model_name='hidroextra',
            name='rio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rio'),
        ),
    ]
