# Generated by Django 3.0.6 on 2020-08-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200825_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('rede_id', models.BigIntegerField(default=0, verbose_name='Rede ID')),
            ],
        ),
        migrations.AddField(
            model_name='estacao',
            name='rede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Rede'),
        ),
    ]
