# Generated by Django 3.0.6 on 2020-08-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200825_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacao',
            name='rede',
        ),
        migrations.DeleteModel(
            name='Rede',
        ),
    ]
