# Generated by Django 3.0.6 on 2020-08-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20200825_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rede',
            old_name='slug_r',
            new_name='slug',
        ),
    ]
