# Generated by Django 3.0.6 on 2020-08-25 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200825_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='hidroextra',
            name='rede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Rede'),
        ),
    ]
