# Generated by Django 3.0.6 on 2020-08-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_parametrounits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametro',
            name='freq',
        ),
    ]
