# Generated by Django 3.0.6 on 2020-09-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20200901_1612'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParametroUnits',
            new_name='ParametroUnit',
        ),
    ]
