# Generated by Django 3.0.6 on 2020-09-17 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20200901_1612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstacaoParamUnits',
        ),
    ]
